### ISSUE TITLE
Getting this error every time

### ISSUE THREAD

**Issue by harambesson** [RandomBananazz/AutoWaifuClaimerV3#3]
Every time I try to run bot.py, it ends up just typing $tu once then will immediately close the browser and disconnect. 
Here is a log from what happens every time: 

2020-12-31 10:11:37,310 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2020-12-31 10:11:37,310 - root - INFO - Parsing likelist
2020-12-31 10:11:37,326 - root - INFO - Starting browser thread
2020-12-31 10:11:37,326 - browsers - INFO - Browser thread started
2020-12-31 10:11:37,326 - discord.client - INFO - logging in using static token
2020-12-31 10:11:37,326 - browsers - INFO - Attempting to open Discord in browser
2020-12-31 10:11:37,744 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2020-12-31 10:11:37,876 - discord.gateway - INFO - Websocket closed with 4000, attempting a reconnect.
2020-12-31 10:11:37,876 - discord.client - INFO - Got a request to RESUME the websocket.
2020-12-31 10:11:38,247 - discord.gateway - INFO - Shard ID None has sent the RESUME payload.
2020-12-31 10:11:38,347 - discord.gateway - INFO - Shard ID None session has been invalidated.
2020-12-31 10:11:38,394 - discord.client - INFO - Got a request to IDENTIFY the websocket.
2020-12-31 10:11:41,759 - browsers - INFO - Logging in with provided credentials (this may take up to 30 seconds)
2020-12-31 10:11:43,683 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2020-12-31 10:11:43,852 - discord.gateway - INFO - Shard ID None has connected to Gateway: ["gateway-prd-main-zvwd",{"micros":122192,"calls":["discord-sessions-prd-2-65",{"micros":119619,"calls":["start_session",{"micros":67318,"calls":["api-prd-main-f6tc",{"micros":64821,"calls":["get_user",{"micros":2798},"add_authorized_ip",{"micros":32314},"get_guilds",{"micros":8490},"coros_wait",{"micros":0}]}]},"guilds_connect",{"micros":1,"calls":[]},"presence_connect",{"micros":44016,"calls":[]}]}]}] (Session ID: EDITED OUT).
2020-12-31 10:11:50,226 - browsers - INFO - Login successful to server EDITED OUT and channel EDITED OUT
2020-12-31 10:11:50,226 - root - INFO - Bot connected as autoclaim with ID EDITED OUT
2020-12-31 10:11:50,611 - root - INFO - Attempting to parse $tu command
2020-12-31 10:11:50,611 - browsers - INFO - Sending text: $tu
2020-12-31 10:11:53,624 - root - CRITICAL - Could not parse $tu command, quitting (try again)
2020-12-31 10:11:54,625 - discord.gateway - INFO - Websocket closed with 1000, cannot reconnect.

**Comment by monkiilongo** [comment]
I ran it again to get everything, the post above was just what was in the logs notepad. 

2020-12-31 10:11:37,310 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2020-12-31 10:11:37,310 - root - INFO - Parsing likelist
2020-12-31 10:11:37,326 - root - INFO - Starting browser thread
2020-12-31 10:11:37,326 - browsers - INFO - Browser thread started
2020-12-31 10:11:37,326 - discord.client - INFO - logging in using static token
2020-12-31 10:11:37,326 - browsers - INFO - Attempting to open Discord in browser
2020-12-31 10:11:37,744 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2020-12-31 10:11:37,876 - discord.gateway - INFO - Websocket closed with 4000, attempting a reconnect.
2020-12-31 10:11:37,876 - discord.client - INFO - Got a request to RESUME the websocket.
2020-12-31 10:11:38,247 - discord.gateway - INFO - Shard ID None has sent the RESUME payload.
2020-12-31 10:11:38,347 - discord.gateway - INFO - Shard ID None session has been invalidated.
2020-12-31 10:11:38,394 - discord.client - INFO - Got a request to IDENTIFY the websocket.
2020-12-31 10:11:41,759 - browsers - INFO - Logging in with provided credentials (this may take up to 30 seconds)
2020-12-31 10:11:43,683 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2020-12-31 10:11:43,852 - discord.gateway - INFO - Shard ID None has connected to Gateway: ["gateway-prd-main-zvwd",{"micros":122192,"calls":["discord-sessions-prd-2-65",{"micros":119619,"calls":["start_session",{"micros":67318,"calls":["api-prd-main-f6tc",{"micros":64821,"calls":["get_user",{"micros":2798},"add_authorized_ip",{"micros":32314},"get_guilds",{"micros":8490},"coros_wait",{"micros":0}]}]},"guilds_connect",{"micros":1,"calls":[]},"presence_connect",{"micros":44016,"calls":[]}]}]}] (Session ID: EDITED OUT).
2020-12-31 10:11:50,226 - browsers - INFO - Login successful to server EDITED OUT and channel EDITED OUT
2020-12-31 10:11:50,226 - root - INFO - Bot connected as autoclaim with ID EDITED OUT
2020-12-31 10:11:50,611 - root - INFO - Attempting to parse $tu command
2020-12-31 10:11:50,611 - browsers - INFO - Sending text: $tu
2020-12-31 10:11:53,624 - root - CRITICAL - Could not parse $tu command, quitting (try again)
2020-12-31 10:11:54,625 - discord.gateway - INFO - Websocket closed with 1000, cannot reconnect.

**Comment by monkiilongo** [comment]
I ran it again so I could get the entire message, the above was just what was in the logs text file. 

2020-12-31 10:33:18,112 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2020-12-31 10:33:18,122 - root - INFO - Parsing likelist
2020-12-31 10:33:18,131 - root - INFO - Starting browser thread
2020-12-31 10:33:18,133 - browsers - INFO - Browser thread started
2020-12-31 10:33:18,133 - discord.client - INFO - logging in using static token
2020-12-31 10:33:18,133 - browsers - INFO - Attempting to open Discord in browser
2020-12-31 10:33:18,605 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2020-12-31 10:33:18,775 - discord.gateway - INFO - Shard ID None has connected to Gateway: ["gateway-prd-main-w599",{"micros":97490,"calls":["discord-sessions-prd-2-9",{"micros":96260,"calls":["start_session",{"micros":65666,"calls":["api-prd-main-lwvs",{"micros":56764,"calls":["get_user",{"micros":3687},"add_authorized_ip",{"micros":7249},"get_guilds",{"micros":15559},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":21779,"calls":[]}]}]}] (Session ID: 548c2512f4a52ea11e812e752bdef8dd).
2020-12-31 10:33:22,523 - browsers - INFO - Logging in with provided credentials (this may take up to 30 seconds)
2020-12-31 10:33:27,700 - browsers - INFO - Login successful to server DELETED and channel DELETED
2020-12-31 10:33:27,700 - root - INFO - Bot connected as autoclaim with ID DELETED
2020-12-31 10:33:28,085 - root - INFO - Attempting to parse $tu command
2020-12-31 10:33:28,085 - browsers - INFO - Sending text: $tu
2020-12-31 10:33:38,084 - root - CRITICAL - Could not parse $tu command, quitting (try again)
2020-12-31 10:33:39,742 - discord.gateway - INFO - Websocket closed with 1000, cannot reconnect.
Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\DELETED\Desktop\AutoWaifuClaimerV3-3\AutoWaifuClaimerV3-3\bot.py", line 133, in on_ready
    await client.wait_for('message', check=parse_tu, timeout=10)
  File "C:\Users\DELETED\AppData\Local\Programs\Python\Python38\lib\asyncio\tasks.py", line 490, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\DELETED\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\DELETED\Desktop\AutoWaifuClaimerV3-3\AutoWaifuClaimerV3-3\bot.py", line 137, in on_ready
    await close_bot()
  File "C:\Users\DELETED\Desktop\AutoWaifuClaimerV3-3\AutoWaifuClaimerV3-3\bot.py", line 67, in close_bot
    client.loop.close()
  File "C:\Users\DELETED\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 675, in close
    raise RuntimeError("Cannot close a running event loop")
RuntimeError: Cannot close a running event loop
Traceback (most recent call last):
  File "C:\Users\DELETED\Desktop\AutoWaifuClaimerV3-3\AutoWaifuClaimerV3-3\bot.py", line 282, in <module>
    browser.close()
  File "C:\Users\DELETED\Desktop\AutoWaifuClaimerV3-3\AutoWaifuClaimerV3-3\browsers.py", line 141, in close
    self.driver.close()
  File "C:\Users\DELETED\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 688, in close
    self.execute(Command.CLOSE)
  File "C:\Users\DELETED\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\DELETED\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: Tried to run command without establishing a connection

**Comment by harambesson** [comment]
I ran it again so I could get the entire message, the above was just what was in the logs text file.

2020-12-31 10:33:18,112 - discord.client - WARNING - PyNaCl is not installed, voice will NOT be supported
2020-12-31 10:33:18,122 - root - INFO - Parsing likelist
2020-12-31 10:33:18,131 - root - INFO - Starting browser thread
2020-12-31 10:33:18,133 - browsers - INFO - Browser thread started
2020-12-31 10:33:18,133 - discord.client - INFO - logging in using static token
2020-12-31 10:33:18,133 - browsers - INFO - Attempting to open Discord in browser
2020-12-31 10:33:18,605 - discord.gateway - INFO - Shard ID None has sent the IDENTIFY payload.
2020-12-31 10:33:18,775 - discord.gateway - INFO - Shard ID None has connected to Gateway: ["gateway-prd-main-w599",{"micros":97490,"calls":["discord-sessions-prd-2-9",{"micros":96260,"calls":["start_session",{"micros":65666,"calls":["api-prd-main-lwvs",{"micros":56764,"calls":["get_user",{"micros":3687},"add_authorized_ip",{"micros":7249},"get_guilds",{"micros":15559},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":21779,"calls":[]}]}]}] (Session ID: DELETED).
2020-12-31 10:33:22,523 - browsers - INFO - Logging in with provided credentials (this may take up to 30 seconds)
2020-12-31 10:33:27,700 - browsers - INFO - Login successful to server DELETED and channel DELETED
2020-12-31 10:33:27,700 - root - INFO - Bot connected as autoclaim with ID DELETED
2020-12-31 10:33:28,085 - root - INFO - Attempting to parse $tu command
2020-12-31 10:33:28,085 - browsers - INFO - Sending text: $tu
2020-12-31 10:33:38,084 - root - CRITICAL - Could not parse $tu command, quitting (try again)
2020-12-31 10:33:39,742 - discord.gateway - INFO - Websocket closed with 1000, cannot reconnect.
Ignoring exception in on_ready
Traceback (most recent call last):
File "C:\Users\DELETED\Desktop\AutoWaifuClaimerV3-3\AutoWaifuClaimerV3-3\bot.py", line 133, in on_ready
await client.wait_for('message', check=parse_tu, timeout=10)
File "C:\Users\DELETED\AppData\Local\Programs\Python\Python38\lib\asyncio\tasks.py", line 490, in wait_for
raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\DELETED\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 333, in _run_event
await coro(*args, **kwargs)
File "C:\Users\DELETED\Desktop\AutoWaifuClaimerV3-3\AutoWaifuClaimerV3-3\bot.py", line 137, in on_ready
await close_bot()
File "C:\Users\DELETED\Desktop\AutoWaifuClaimerV3-3\AutoWaifuClaimerV3-3\bot.py", line 67, in close_bot
client.loop.close()
File "C:\Users\DELETED\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 675, in close
raise RuntimeError("Cannot close a running event loop")
RuntimeError: Cannot close a running event loop
Traceback (most recent call last):
File "C:\Users\DELETED\Desktop\AutoWaifuClaimerV3-3\AutoWaifuClaimerV3-3\bot.py", line 282, in
browser.close()
File "C:\Users\DELETED\Desktop\AutoWaifuClaimerV3-3\AutoWaifuClaimerV3-3\browsers.py", line 141, in close
self.driver.close()
File "C:\Users\DELETED\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 688, in close
self.execute(Command.CLOSE)
File "C:\Users\DELETED\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
self.error_handler.check_response(response)
File "C:\Users\DELETED\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: Tried to run command without establishing a connection

**Comment by MrCatcatsan** [comment]
same here

**Comment by Reloisback** [comment]
I am having the same problem. Any solution found?

**Comment by JasonYuan869** [comment]
Sorry about this guys! I'll look into it soon!

**Comment by Reloisback** [comment]
> Sorry about this guys! I'll look into it soon!

I am waiting eagerly, I wish you good work.

**Comment by harambesson** [comment]
> Sorry about this guys! I'll look into it soon!

Sounds good, thanks for the reply.

**Comment by jeroldcamacho** [comment]
having the same problem too

**Comment by Uzumaki-Boruto** [comment]
Same problem here. Is there any solution?

**Comment by dannysollo** [comment]
Also have this issue

**Comment by nanocapo10** [comment]
Same problem here. Is there any solution?

**Comment by qu1t6** [comment]
Same here
