### ISSUE TITLE
Discord error: 403 forbidden

### ISSUE THREAD

**Issue by seriaati** [RandomBananazz/AutoWaifuClaimerV3#9]
Ran bot.py and this error shows up:
```
Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Administrator\AutoWaifuClaimerV3\bot.py", line 124, in on_ready
    roll_channel = await client.fetch_channel(config.CHANNEL_ID)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\client.py", line 1447, in fetch_channel
    data = await self.http.get_channel(channel_id)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\http.py", line 241, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access
```

**Comment by TheMisteryManESP** [comment]
Did you ever get a fix for this?

**Comment by seriaati** [comment]
> Did you ever get a fix for this?

No, use [this](https://github.com/vivinano/MudaeAutoBot) instead.
